language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
env:
  - DJANGO_VERSION=2.0
  - DJANGO_VERSION=1.11.8
  - DJANGO_VERSION=1.10.8
  - DJANGO_VERSION=1.8.18
install:
  # Build/test dependencies
 - pip install -r requirements.txt -r requirements-dev.txt
 - pip install Django==$DJANGO_VERSION
#before_script:
script:
  - python setup.py code_quality
  - python setup.py test
  - python setup.py install
  - fab init_demo
  - make -C docs html-check

matrix:
    exclude:
        # Django 2.0 no longer supports python2
        - env: DJANGO_VERSION=2.0
          python: "2.7"

#notifications:
#  irc:
#    channels: "irc.freenode.org#fabric"
#    template:
#      - "%{repository}@%{branch}: %{message} (%{build_url})"
#    on_success: change
#    on_failure: change
#  email: false
